# TradingAgents/graph/signal_processing.py

import re
from typing import Literal, cast

from pydantic import Field, BaseModel, ConfigDict, SkipValidation

from tradingagents.llm import ChatModel

TradeSignal = Literal["BUY", "SELL", "HOLD"]
_DECISION_PATTERN = re.compile(r"\b(BUY|SELL|HOLD)\b", re.IGNORECASE)
_FINAL_PATTERN = re.compile(
    r"FINAL\s+TRANSACTION\s+PROPOSAL\s*:\s*(?:\*\*)?\s*(BUY|SELL|HOLD)\s*(?:\*\*)?", re.IGNORECASE
)


def extract_trade_signal(full_signal: object) -> TradeSignal:
    """Extract a canonical BUY/SELL/HOLD decision without another LLM call.

    The risk manager should ideally emit the explicit
    ``FINAL TRANSACTION PROPOSAL`` marker. If that marker is absent, fall back
    to all decision tokens in the text and accept only unambiguous output.
    """
    if isinstance(full_signal, list):
        text = "\n".join(
            item.get("text", "") if isinstance(item, dict) else str(item) for item in full_signal
        )
    else:
        text = str(full_signal or "")

    final_matches = [match.upper() for match in _FINAL_PATTERN.findall(text)]
    if final_matches:
        distinct = set(final_matches)
        if len(distinct) == 1:
            return cast("TradeSignal", final_matches[-1])
        raise ValueError(f"Conflicting final transaction proposals found: {sorted(distinct)}")

    decisions = [match.upper() for match in _DECISION_PATTERN.findall(text)]
    distinct = set(decisions)
    if len(distinct) == 1:
        return cast("TradeSignal", decisions[-1])
    if not distinct:
        raise ValueError("No BUY/SELL/HOLD decision found in final trade decision.")
    raise ValueError(f"Ambiguous trade decision contains multiple signals: {sorted(distinct)}")


class SignalProcessor(BaseModel):
    """Processes trading signals deterministically to extract actionable decisions."""

    model_config = ConfigDict(arbitrary_types_allowed=True)

    # --- User-configurable fields ---

    quick_thinking_llm: SkipValidation[ChatModel | None] = Field(
        default=None,
        title="Quick Thinking LLM",
        description="Deprecated compatibility field; signal extraction is deterministic",
    )

    # --- Public methods ---

    def process_signal(self, full_signal: str) -> str:
        """Process a full trading signal to extract the core decision.

        Args:
            full_signal (str): The full signal text generated by analysts.

        Returns:
            str: Extracted decision (SELL, BUY, or HOLD).
        """
        return extract_trade_signal(full_signal)
