# TradingAgents/graph/signal_processing.py

from pydantic import Field, BaseModel, ConfigDict, SkipValidation

from tradingagents.llm import ChatModel


class SignalProcessor(BaseModel):
    """Processes trading signals to extract actionable decisions."""

    model_config = ConfigDict(arbitrary_types_allowed=True)

    # --- User-configurable fields ---

    quick_thinking_llm: SkipValidation[ChatModel] = Field(
        ...,
        title="Quick Thinking LLM",
        description="LLM instance used for extracting investment decisions from signals",
    )

    # --- Public methods ---

    def process_signal(self, full_signal: str) -> str:
        """Process a full trading signal to extract the core decision.

        Args:
            full_signal (str): The full signal text generated by analysts.

        Returns:
            str: Extracted decision (SELL, BUY, or HOLD).
        """
        messages = [
            (
                "system",
                "You are an efficient assistant designed to analyze paragraphs or financial reports provided by a group of analysts. Your task is to extract the investment decision: SELL, BUY, or HOLD. Provide only the extracted decision (SELL, BUY, or HOLD) as your output, without adding any additional text or information.",
            ),
            ("human", full_signal),
        ]

        return self.quick_thinking_llm.invoke(messages).content
