# TradingAgents/graph/signal_processing.py

import re
from typing import Any, Literal, cast
import logging

from pydantic import BaseModel

logger = logging.getLogger(__name__)

TradeSignal = Literal["BUY", "SELL", "HOLD"]
_DECISION_PATTERN = re.compile(r"\b(BUY|SELL|HOLD)\b", re.IGNORECASE)
_FINAL_PATTERN = re.compile(
    r"FINAL\s+TRANSACTION\s+PROPOSAL\s*:\s*(?:\*\*)?\s*(BUY|SELL|HOLD)\s*(?:\*\*)?", re.IGNORECASE
)


def extract_trade_signal(full_signal: str | list[str | dict[str, Any]] | None) -> TradeSignal:
    """Extract a canonical BUY/SELL/HOLD decision without another LLM call.

    Always returns one of BUY/SELL/HOLD; logs a warning and defaults to
    HOLD when the input is empty, missing the canonical
    ``FINAL TRANSACTION PROPOSAL`` line, or contains conflicting signals.
    Never raises — a malformed risk-judge response must not abort a paid
    LangGraph run after every other agent has already produced output.
    """
    if isinstance(full_signal, list):
        text = "\n".join(
            item.get("text", "") if isinstance(item, dict) else str(item) for item in full_signal
        )
    else:
        text = str(full_signal or "")

    final_matches = [match.upper() for match in _FINAL_PATTERN.findall(text)]
    if final_matches:
        # The last FINAL marker wins because risk judges often quote the
        # trader's earlier proposal ("the trader proposed BUY but I
        # recommend SELL") before stating their own conclusion.
        return cast("TradeSignal", final_matches[-1])

    decisions = [match.upper() for match in _DECISION_PATTERN.findall(text)]
    if not decisions:
        logger.warning("Risk judge output contained no BUY/SELL/HOLD token; defaulting to HOLD.")
        return "HOLD"

    distinct = set(decisions)
    if len(distinct) == 1:
        return cast("TradeSignal", decisions[-1])

    logger.warning(
        "Risk judge output is ambiguous (signals: %s); defaulting to HOLD.", sorted(distinct)
    )
    return "HOLD"


class SignalProcessor(BaseModel):
    """Processes trading signals deterministically to extract actionable decisions."""

    def process_signal(self, full_signal: str) -> TradeSignal:
        """Process a full trading signal to extract the core decision.

        Args:
            full_signal (str): The full signal text generated by analysts.

        Returns:
            TradeSignal: Extracted decision (BUY, SELL, or HOLD). Defaults
            to HOLD when the input is empty or ambiguous.
        """
        return extract_trade_signal(full_signal)
